-- MySQL Script generated by MySQL Workbench
-- Fri Jan 13 10:16:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vinodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vinodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vinodb` ;
USE `vinodb` ;

-- -----------------------------------------------------
-- Table `vinodb`.`vino__type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__bouteille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__bouteille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NULL,
  `code_saq` INT(100) NULL,
  `type` INT(11) NULL,
  `image` VARCHAR(200) NULL,
  `code_saq` INT NULL,
  `pays` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `prix` VARCHAR(45) NULL,
  `url` VARCHAR(200) NULL,
  `url_img` VARCHAR(200) NULL,
  `couleur` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__usager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__usager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomusager` VARCHAR(200) NULL,
  `motdepasse` VARCHAR(200) NULL,
  `date_creation` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__cellier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__cellier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usager` INT(20) NULL,
  `nom_cellier` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_usager`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__usager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usager` INT(20) NULL,
  `commentaire` VARCHAR(200) NULL,
  `id_bouteille` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_usager`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__usager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__cellier_has_vino__bouteille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__cellier_has_vino__bouteille` (
  `vino__cellier_id` INT NOT NULL,
  `vino__bouteille_id` INT NOT NULL,
  `quantite` VARCHAR(45) NULL,
  PRIMARY KEY (`vino__cellier_id`, `vino__bouteille_id`),
  INDEX `fk_vino__cellier_has_vino__bouteille_vino__bouteille1_idx` (`vino__bouteille_id` ASC) VISIBLE,
  INDEX `fk_vino__cellier_has_vino__bouteille_vino__cellier1_idx` (`vino__cellier_id` ASC) VISIBLE,
  CONSTRAINT `fk_vino__cellier_has_vino__bouteille_vino__cellier1`
    FOREIGN KEY (`vino__cellier_id`)
    REFERENCES `vinodb`.`vino__cellier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vino__cellier_has_vino__bouteille_vino__bouteille1`
    FOREIGN KEY (`vino__bouteille_id`)
    REFERENCES `vinodb`.`vino__bouteille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__bouteille_personalize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__bouteille_personalize` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NULL,
  `description` VARCHAR(200) NULL,
  `vino__cellier_has_vino__bouteille_vino__cellier_id` INT NOT NULL,
  `vino__cellier_has_vino__bouteille_vino__bouteille_id` INT NOT NULL,
  `provenance` VARCHAR(45) NULL,
  `couleur` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vino__bouteille_personalize_vino__cellier_has_vino__bout_idx` (`vino__cellier_has_vino__bouteille_vino__cellier_id` ASC, `vino__cellier_has_vino__bouteille_vino__bouteille_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__bouteille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vino__bouteille_personalize_vino__cellier_has_vino__boutei1`
    FOREIGN KEY (`vino__cellier_has_vino__bouteille_vino__cellier_id` , `vino__cellier_has_vino__bouteille_vino__bouteille_id`)
    REFERENCES `vinodb`.`vino__cellier_has_vino__bouteille` (`vino__cellier_id` , `vino__bouteille_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
