-- MySQL Script generated by MySQL Workbench
-- Mon Jan  9 17:31:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vinodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vinodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vinodb` ;
USE `vinodb` ;

-- -----------------------------------------------------
-- Table `vinodb`.`vino__type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__bouteille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__bouteille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NULL,
  `image` VARCHAR(200) NULL,
  `code_saq` VARCHAR(50) NULL,
  `pays` VARCHAR(50) NULL,
  `description` VARCHAR(200) NULL,
  `prix_saq` FLOAT NULL,
  `url_saq` VARCHAR(200) NULL,
  `url_img` VARCHAR(200) NULL,
  `format` VARCHAR(20) NULL,
  `type` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `type`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__usager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__usager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomusager` VARCHAR(200) NULL,
  `motdepasse` VARCHAR(200) NULL,
  `prenom_nomusager` VARCHAR(200) NULL,
  `nom_nomusager` VARCHAR(200) NULL,
  `adresse` VARCHAR(200) NULL,
  `date_creation` TIMESTAMP NULL,
  `date_modification` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__cellier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__cellier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_bouteille` INT NULL,
  `date_achat` DATE NULL,
  `garde_jusqua` VARCHAR(200) NULL,
  `notes` VARCHAR(200) NULL,
  `prix` FLOAT NULL,
  `quantite` INT NULL,
  `millesime` INT(11) NULL,
  `id_usager` INT(20) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_bouteille`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__bouteille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usager`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__usager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vinodb`.`vino__commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vinodb`.`vino__commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usager` INT(20) NULL,
  `commentaire` VARCHAR(200) NULL,
  `id_bouteille` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_usager`
    FOREIGN KEY (`id`)
    REFERENCES `vinodb`.`vino__usager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
